version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"  # Corrected port mapping
    volumes:
      - ./src:/app/src  # Live reload
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
